name: CI tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v5
    - name: Setup pixi
      uses: prefix-dev/setup-pixi@v0.9.0
      with:
        environments: >-
          default
          test
    - name: Run pytest
      run: |
        pixi run -e test pytest
